use crate::bib::types::{
    Articulo, Coordenada, Direccion, Escala, Escena, Fondo, Prohibido, Silla, Sprite, Talla,
};
use once_cell::sync::Lazy;

pub const SUEÑO: u64 = 10000;

pub static LISTA_ESCENA: Lazy<[Escena; 1]> = Lazy::new(|| {
    [
        Escena {
            clave: String::from("estudio abierto de trabajo"),
            mundo: Talla {
                altura: 830.0,
                anchura: 1512.0,
            },
            fondo: Fondo {
                uri: String::from("QmQho15EawdPjxhZ6QcnFoGHiEV8r2dTS1u7TczQv9cd44"),
                etiqueta: String::from("fondo"),
                altura: 830.0,
                anchura: 1512.0,
                sitio: Coordenada { x: 0, y: 0 },
            },
            imagen: String::from("QmcWnwXob7yRrZg4gUJyqo3Vtsabk8jWL5eL7NEn5HhDe7"),
            sillas: vec![
                Silla {
                    anim: Direccion::Sofa,
                    profundidad: false,
                    x_adjustado: 800.0,
                    y_adjustado: 210.0,
                    etiqueta: String::from("sofaUno"),
                    sitio: Coordenada { x: 779, y: 200 },
                    talla: Coordenada { x: 220, y: 120 },
                    uri: String::from("QmQfqKAD2Hepe9kQ9VxBSNmwZrywCvuPrnAr5AiF4bMvwB"),
                    escala: Escala { x: 1.2, y: 1.2 },
                    depth: Some(0.0),
                    par: None,
                },
                Silla {
                    anim: Direccion::Sofa,
                    profundidad: false,
                    x_adjustado: 1250.0,
                    y_adjustado: 200.0,
                    etiqueta: String::from("sofaDos"),
                    sitio: Coordenada { x: 1250, y: 200 },
                    talla: Coordenada { x: 220, y: 120 },
                    uri: String::from("QmUFsXQpp1ZZWKWCnHAED4pgZgeLSBnp4ofMz9ae1BkhAR"),
                    escala: Escala { x: 1.2, y: 1.2 },
                    depth: Some(0.0),
                    par: None,
                },
                Silla {
                    anim: Direccion::Silla,
                    profundidad: true,
                    x_adjustado: 1330.0,
                    y_adjustado: 280.0,
                    etiqueta: String::from("silla1"),
                    sitio: Coordenada { x: 1322, y: 325 },
                    talla: Coordenada { x: 92, y: 116 },
                    uri: String::from("QmariT81Kgxw4mNHCt8wGHmgH5avzrZt2r6vNiik4qeSwK"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    par: Some(String::from("escritorio1")),
                    depth: None,
                },
                Silla {
                    anim: Direccion::Silla,
                    profundidad: true,
                    x_adjustado: 1330.0,
                    y_adjustado: 420.0,
                    etiqueta: String::from("silla2"),
                    sitio: Coordenada { x: 1322, y: 470 },
                    talla: Coordenada { x: 89, y: 109 },
                    uri: String::from("Qmc8VyBMDALMJJknadELsL9SBQuYSuTHpa3e1SqfX61Egn"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    par: Some(String::from("escritorio2")),
                    depth: None,
                },
                Silla {
                    anim: Direccion::Silla,
                    profundidad: true,
                    x_adjustado: 1000.0,
                    y_adjustado: 285.0,
                    etiqueta: String::from("silla3"),
                    sitio: Coordenada { x: 993, y: 325 },
                    talla: Coordenada { x: 100, y: 108 },
                    uri: String::from("QmUuHUnrMHhusH1JrgG6WonoCUxG1t7LQe348gru2d4uHM"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    par: Some(String::from("escritorio3")),
                    depth: None,
                },
                Silla {
                    anim: Direccion::Silla,
                    profundidad: true,
                    x_adjustado: 1000.0,
                    y_adjustado: 440.0,
                    uri: String::from("QmfZPky9neYWSuQcZ7wtyajqMCRPBaq7WiPjaab4ZxC8PZ"),
                    etiqueta: String::from("silla4"),
                    sitio: Coordenada { x: 999, y: 485 },
                    talla: Coordenada { x: 98, y: 103 },
                    escala: Escala { x: 1.0, y: 1.0 },
                    par: Some(String::from("escritorio4")),
                    depth: None,
                },
            ],
            objetos: vec![
                Articulo {
                    etiqueta: String::from("pared"),
                    sitio: Coordenada { x: 850, y: 89 },
                    talla: Coordenada { x: 1400, y: 190 },
                    uri: String::from("QmcR8PpyDhRaUzJJW5UoxhnyzqNk88imgXS2MGuhgfYsYK"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: Some(0.0),
                },
                Articulo {
                    etiqueta: String::from("nevera"),
                    sitio: Coordenada { x: 145, y: 170 },
                    talla: Coordenada { x: 320, y: 360 },
                    uri: String::from("QmaGoMNwYt7aEgG6AoKGmDdmWUQgshQ8KtASkgoHKgmcS2"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: Some(0.0),
                },
                Articulo {
                    etiqueta: String::from("maquina"),
                    sitio: Coordenada { x: 470, y: 200 },
                    talla: Coordenada { x: 190, y: 225 },
                    uri: String::from("QmVubKFGVcdfZS2pSEhmK8DtpFWbiC8H2BX11VPTd9xnNp"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: Some(0.0),
                },
                Articulo {
                    etiqueta: String::from("alfombra"),
                    sitio: Coordenada { x: 410, y: 520 },
                    talla: Coordenada { x: 320, y: 200 },
                    uri: String::from("QmQaZhrMnuwkKbP2UbYtnMxRiUcpZfNGyuEhGuqd7xcFAj"),
                    escala: Escala { x: 1.5, y: 1.2 },
                    profundidad: Some(0.0),
                },
                Articulo {
                    etiqueta: String::from("arcade"),
                    sitio: Coordenada { x: 1442, y: 700 },
                    talla: Coordenada { x: 163, y: 267 },
                    uri: String::from("QmaNMrJo7TqEpvsveTFJk7zwBbS4SukM3gnuVwhiY5sCoa"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: None,
                },
                Articulo {
                    etiqueta: String::from("audio1"),
                    sitio: Coordenada { x: 756, y: 772 },
                    talla: Coordenada { x: 160, y: 117 },
                    uri: String::from("QmYrGLoU35kwH9HyVLi283hG2GzX1fbxuszHT3j1qfAs8G"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: Some(1000.0),
                },
                Articulo {
                    etiqueta: String::from("audio2"),
                    sitio: Coordenada { x: 916, y: 765 },
                    talla: Coordenada { x: 160, y: 130 },
                    uri: String::from("QmQA2cgeuAMvLSqj75CWrhmNhKoQV2GKapy94Co6WmWQVi"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: Some(1000.0),
                },
                Articulo {
                    etiqueta: String::from("planta1"),
                    sitio: Coordenada { x: 530, y: 788 },
                    talla: Coordenada { x: 97, y: 84 },
                    uri: String::from("QmXYg1FC5zTHXHP1czJmsusC9DT33JCwHnLacYAui1HH84"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: Some(1000.0),
                },
                Articulo {
                    etiqueta: String::from("planta2"),
                    sitio: Coordenada { x: 605, y: 779 },
                    talla: Coordenada { x: 75, y: 104 },
                    uri: String::from("QmdcSwsasjt18R7Hey77X6idnW9qz25Q1XkVsHT7inqbm7"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: Some(1000.0),
                },
                Articulo {
                    etiqueta: String::from("capsula"),
                    sitio: Coordenada { x: 40, y: 468 },
                    talla: Coordenada { x: 95, y: 302 },
                    uri: String::from("QmYjXKxmyRQHf6fDdqEaNPEdc3W7gcFuNxogsVL38kR3M9"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: None,
                },
                Articulo {
                    etiqueta: String::from("telefono"),
                    sitio: Coordenada { x: 40, y: 710 },
                    talla: Coordenada { x: 86, y: 242 },
                    uri: String::from("QmSz2dcSRdX9vtxpXH91dS4pe8PAkAakbwfb4mGZNwunkk"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: None,
                },
            ],
            profundidad: vec![
                Articulo {
                    etiqueta: String::from("panelDeControl"),
                    uri: String::from("QmWMPF4YYvRLGW4F76kufDSxg2LnYojDNZK7cfdkwQxdXw"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    sitio: Coordenada { x: 1320, y: 630 },
                    talla: Coordenada { x: 390, y: 228 },
                    profundidad: None,
                },
                Articulo {
                    etiqueta: String::from("escritorio1"),
                    sitio: Coordenada { x: 1342, y: 310 },
                    talla: Coordenada { x: 319, y: 186 },
                    uri: String::from("QmWtr9iRZ4HiPe1PBxrJfiB9hEQNa3GWxtipt7hqFvBPvs"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: None,
                },
                Articulo {
                    etiqueta: String::from("escritorio2"),
                    sitio: Coordenada { x: 1342, y: 430 },
                    talla: Coordenada { x: 307, y: 177 },
                    uri: String::from("QmTwbtXhizeCxBbZk9Nbd3yrt67kcB7Ytm6sKAzx5rFtCd"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: None,
                },
                Articulo {
                    etiqueta: String::from("escritorio3"),
                    sitio: Coordenada { x: 1013, y: 310 },
                    talla: Coordenada { x: 307, y: 165 },
                    uri: String::from("Qmcy6nTw4YaGj8AEtba2WVm8gYy1vj9LbyMNk9qGptz4ny"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: None,
                },
                Articulo {
                    etiqueta: String::from("escritorio4"),
                    sitio: Coordenada { x: 1019, y: 440 },
                    talla: Coordenada { x: 307, y: 160 },
                    uri: String::from("Qmd8VH1yPkPGtxoRM1bdAvLJnjyTG21pgswddCVnECxDHh"),
                    escala: Escala { x: 1.0, y: 1.0 },
                    profundidad: None,
                },
            ],
            sprites: vec![
                Sprite {
                    etiqueta: String::from("muchacho-estudio"),
                    uri: String::from("QmUHDrL3JTUMwztqyzr8cUdCjYLpjET9pRXrLTRPtfgSBx"),
                    x: 383.0,
                    y: 576.0,
                    tapa: String::from("QmXME5CUW3PdBVqsGx9JJznB1dWYUBbem1cmQgtEBX2vp7"),
                    altura: 600.0,
                    anchura: 300.0,
                    anchura_borde: 600.0,
                    altura_borde: 600.0,
                    margen: 0.0,
                    marco_inicio: 0.0,
                    marco_final: 143.0,
                    escala: Escala { x: 0.5, y: 0.5 },
                    movimientos_max: 6.0,
                },
                Sprite {
                    etiqueta: String::from("chica-estudio"),
                    uri: String::from("QmSXHXcEe9XWiVLL228NK12s9o68uWVQRVn8oedPE7boYf"),
                    x: 383.0,
                    y: 576.0,
                    tapa: String::from("QmczmZzdHG7fmYtCUDS58faHs1d1pzENEa3x8WxscyNhRH"),
                    altura: 600.0,
                    anchura: 300.0,
                    anchura_borde: 600.0,
                    altura_borde: 600.0,
                    margen: 0.0,
                    marco_inicio: 0.0,
                    marco_final: 143.0,
                    escala: Escala { x: 0.5, y: 0.5 },
                    movimientos_max: 4.0,
                },
                Sprite {
                    etiqueta: String::from("dama-estudio"),
                    uri: String::from("QmcdYHqQQkLd77BsdmaBc7JtK8uoett4SLgPFAYa1GLtyH"),
                    x: 383.0,
                    y: 576.0,
                    tapa: String::from("QmZW3DWmPRT65ctLHzpsBkFR8wUkSfD7z6twDtyhHCusg7"),
                    altura: 600.0,
                    anchura: 300.0,
                    anchura_borde: 600.0,
                    altura_borde: 600.0,
                    margen: 0.0,
                    marco_inicio: 0.0,
                    marco_final: 143.0,
                    escala: Escala { x: 0.5, y: 0.5 },
                    movimientos_max: 10.0,
                },
            ],
            prohibido: vec![
                Prohibido {
                    x: 0.0,
                    y: 0.0,
                    altura: 150.0,
                    anchura: 1512.0,
                },
                Prohibido {
                    x: 0.0,
                    y: 0.0,
                    altura: 250.0,
                    anchura: 250.0,
                },
                Prohibido {
                    x: 1349.0,
                    y: 670.0,
                    altura: 200.0,
                    anchura: 163.0,
                },
                Prohibido {
                    x: 357.0,
                    y: 0.0,
                    altura: 190.0,
                    anchura: 225.0,
                },
                Prohibido {
                    x: 0.0,
                    y: 0.0,
                    altura: 830.0,
                    anchura: 80.0,
                },
                Prohibido {
                    x: 1122.0,
                    y: 590.0,
                    altura: 50.0,
                    anchura: 390.0,
                },
                Prohibido {
                    x: 1182.0,
                    y: 220.0,
                    altura: 100.0,
                    anchura: 330.0,
                },
                Prohibido {
                    x: 1205.0,
                    y: 350.0,
                    altura: 100.0,
                    anchura: 330.0,
                },
                Prohibido {
                    x: 859.0,
                    y: 220.0,
                    altura: 100.0,
                    anchura: 330.0,
                },
                Prohibido {
                    x: 865.0,
                    y: 360.0,
                    altura: 100.0,
                    anchura: 350.0,
                },
                Prohibido {
                    x: 845.0,
                    y: 360.0,
                    altura: 150.0,
                    anchura: 30.0,
                },
                Prohibido {
                    x: 645.0,
                    y: 0.0,
                    altura: 160.0,
                    anchura: 350.0,
                },
                Prohibido {
                    x: 1075.0,
                    y: 0.0,
                    altura: 160.0,
                    anchura: 350.0,
                },
            ],
        },
        //  Escena {
        //     clave: "ático de intercambio de varianza",
        //     mundo: { height: 870, width: 1700 },
        //     fondo: {
        //       uri: "QmaHcNASXr5YpgYj7uDBmt9caUL97GiDWM73JHK4E1YoKv",
        //       etiqueta: "fondo",
        //       displayHeight: 570,
        //       displayWidth: 1700,
        //       sitio: { x: 0, y: 330 },
        //     },
        //     cover: "Qmab76vqVsvmTeDFH3YTNRBijE7fujSkyqsEqDz4vH7quH",
        //     objects: [
        //       {
        //         etiqueta: "ventanas",
        //         sitio: { x: 850, y: 170 },
        //         talla: { x: 1700, y: 360 },
        //         uri: "QmV1ozQMtiCyqSEGKxg63DDRwhL4wYCJqzegMheARrXjxW",
        //         escala: { x: 1.5, y: 1 },
        //         profundidad: 0,
        //       },
        //       {
        //         etiqueta: "monitor",
        //         sitio: { x: 850, y: 160 },
        //         talla: { x: 280, y: 200 },
        //         uri: "QmSUovQbp8JByka4Nk8t3DvxZ3kXgRuVU9kh67V5kn9YgG",
        //         escala: { x: 1.3, y: 1.1 },
        //         profundidad: 0,
        //       },
        //     ],
        //     sprites: [
        //       {
        //         etiqueta: "muchacho-ático",
        //         uri: "QmUHDrL3JTUMwztqyzr8cUdCjYLpjET9pRXrLTRPtfgSBx",
        //         x: 383,
        //         y: 576,
        //         cover: "QmXME5CUW3PdBVqsGx9JJznB1dWYUBbem1cmQgtEBX2vp7",
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 6,
        //       },
        //       {
        //         etiqueta: "chica-ático",
        //         uri: "QmSXHXcEe9XWiVLL228NK12s9o68uWVQRVn8oedPE7boYf",
        //         cover: "QmczmZzdHG7fmYtCUDS58faHs1d1pzENEa3x8WxscyNhRH",
        //         x: 383,
        //         y: 576,
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 4,
        //       },
        //     ],
        //     profundidad: [
        //       {
        //         etiqueta: "escritoriosSuperior",
        //         sitio: { x: 850, y: 450 },
        //         talla: { x: 1250, y: 250 },
        //         uri: "QmbW6NieKq5rkqE7F5UDyAVU2g9NF5WYAWCux7Qvuwuh54",
        //         escala: { x: 1, y: 1 },
        //       },
        //       {
        //         etiqueta: "escritoriosInferior",
        //         sitio: { x: 850, y: 650 },
        //         talla: { x: 1100, y: 250 },
        //         uri: "QmTesaW8dD2pkTSsLvi6Nhsf3tXN9NQmfBfmMhLfht1abJ",
        //         escala: { x: 1, y: 1 },
        //       },
        //     ],
        //     prohibited: [
        //       {
        //         x: 0,
        //         y: 0,
        //         width: 1700,
        //         height: 200,
        //       },
        //       {
        //         x: 230,
        //         y: 370,
        //         width: 1300,
        //         height: 150,
        //       },
        //       {
        //         x: 250,
        //         y: 570,
        //         width: 1170,
        //         height: 150,
        //       },
        //     ],
        //     sillas: [
        //       {
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         x_adjustado: 500,
        //         y_adjustado: 460,
        //         etiqueta: "sillaSuperior1",
        //         sitio: { x: 500, y: 500 },
        //         talla: { x: 189, y: 175 },
        //         uri: "QmRb3pPcDnR1e9WLtfqgzRZEiGdSGVWM6N9mFrLHqs16v8",
        //         escala: { x: 1, y: 1 },
        //         par: "escritoriosSuperior",
        //       },
        //       {
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         x_adjustado: 730,
        //         y_adjustado: 460,
        //         etiqueta: "sillaSuperior2",
        //         sitio: { x: 730, y: 500 },
        //         talla: { x: 189, y: 175 },
        //         uri: "QmRb3pPcDnR1e9WLtfqgzRZEiGdSGVWM6N9mFrLHqs16v8",
        //         escala: { x: 1, y: 1 },
        //         par: "escritoriosSuperior",
        //       },
        //       {
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         x_adjustado: 980,
        //         y_adjustado: 460,
        //         etiqueta: "sillaSuperior3",
        //         sitio: { x: 980, y: 500 },
        //         talla: { x: 189, y: 175 },
        //         uri: "QmRb3pPcDnR1e9WLtfqgzRZEiGdSGVWM6N9mFrLHqs16v8",
        //         escala: { x: 1, y: 1 },
        //         par: "escritoriosSuperior",
        //       },
        //       {
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         x_adjustado: 1210,
        //         y_adjustado: 460,
        //         etiqueta: "sillaSuperior4",
        //         sitio: { x: 1210, y: 500 },
        //         talla: { x: 189, y: 175 },
        //         uri: "QmRb3pPcDnR1e9WLtfqgzRZEiGdSGVWM6N9mFrLHqs16v8",
        //         escala: { x: 1, y: 1 },
        //         par: "escritoriosSuperior",
        //       },
        //       {
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         x_adjustado: 550,
        //         y_adjustado: 725,
        //         etiqueta: "sillaInferior6",
        //         sitio: { x: 550, y: 750 },
        //         talla: { x: 189, y: 175 },
        //         uri: "QmRb3pPcDnR1e9WLtfqgzRZEiGdSGVWM6N9mFrLHqs16v8",
        //         escala: { x: 1, y: 1 },
        //         par: "escritoriosInferior",
        //       },
        //       {
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         x_adjustado: 850,
        //         y_adjustado: 725,
        //         etiqueta: "sillaInferior7",
        //         sitio: { x: 850, y: 750 },
        //         talla: { x: 189, y: 175 },
        //         uri: "QmYukvtXPobWiDUdFFCdSJLQ6Pga55unN3fFBAHNWKSprp",
        //         escala: { x: 1, y: 1 },
        //         par: "escritoriosInferior",
        //       },
        //       {
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         x_adjustado: 1150,
        //         y_adjustado: 725,
        //         etiqueta: "sillaInferior8",
        //         sitio: { x: 1150, y: 750 },
        //         talla: { x: 189, y: 175 },
        //         uri: "QmYukvtXPobWiDUdFFCdSJLQ6Pga55unN3fFBAHNWKSprp",
        //         escala: { x: 1, y: 1 },
        //         par: "escritoriosInferior",
        //       },
        //     ],
        //   },
        //   {
        //     clave: "lote de graffiti",
        //     fondo: {
        //       uri: "QmfP6z4Qw4R9zNPP2cz9hJZf2rKCFc9fxggD4ce2r21Zj7",
        //       etiqueta: "fondo",
        //       displayHeight: 620,
        //       displayWidth: 1512,
        //       sitio: { x: 0, y: 230 },
        //     },
        //     cover: "QmVA8di3khf9Fbb1a2JLDk21UdQ4zRoBPLEwRwEwtmQYyp",
        //     sprites: [
        //       {
        //         etiqueta: "muchacho-lote",
        //         uri: "QmUHDrL3JTUMwztqyzr8cUdCjYLpjET9pRXrLTRPtfgSBx",
        //         x: 400,
        //         y: 700,
        //         cover: "QmXME5CUW3PdBVqsGx9JJznB1dWYUBbem1cmQgtEBX2vp7",
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 6,
        //       },
        //       {
        //         etiqueta: "chica-lote",
        //         uri: "QmSXHXcEe9XWiVLL228NK12s9o68uWVQRVn8oedPE7boYf",
        //         cover: "QmczmZzdHG7fmYtCUDS58faHs1d1pzENEa3x8WxscyNhRH",
        //         x: 40,
        //         y: 600,
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 4,
        //       },
        //     ],
        //     objects: [
        //       {
        //         uri: "QmfRKEmaEX24TSkqHjtELGSF687wLoUzgvBp2wF52TR1qJ",
        //         etiqueta: "paredAtras",
        //         sitio: { x: 756, y: 115 },
        //         talla: { x: 1512, y: 230 },
        //         escala: { x: 1.3, y: 1 },
        //         profundidad: 0,
        //       },
        //       {
        //         etiqueta: "rincon",
        //         uri: "QmWUjz1fdY8D9w5nBPERiqPYrKo5sDXYiSKXyaxF64oyx6",
        //         sitio: { x: 1350, y: 220 },
        //         talla: { x: 450, y: 450 },
        //         escala: { x: 1.3, y: 1 },
        //         profundidad: 0,
        //       },
        //       {
        //         etiqueta: "coser",
        //         uri: "QmPJt81SgAJDLRAm8MFQZFt4UAEx5VYdXtjGSfdPu6oq85",
        //         sitio: { x: 910, y: 150 },
        //         talla: { x: 300, y: 200 },
        //         escala: { x: 1.3, y: 1 },
        //         profundidad: 0,
        //       },
        //       {
        //         etiqueta: "estante1",
        //         uri: "QmTHKmEikZvaPMEBVbwDnX5w4Q1PmTbnJbezshPhd5Wgv6",
        //         sitio: { x: 150, y: 150 },
        //         talla: { x: 250, y: 180 },
        //         escala: { x: 1.3, y: 1 },
        //         profundidad: 0,
        //       },
        //       {
        //         etiqueta: "estante2",
        //         uri: "QmaSVU8Xkm1bg8ieqqM6tuJGqW8V7zeAmVwLLN7gpDqy7p",
        //         sitio: { x: 470, y: 155 },
        //         talla: { x: 250, y: 180 },
        //         escala: { x: 1.3, y: 1 },
        //         profundidad: 0,
        //       },
        //       {
        //         etiqueta: "microondas",
        //         uri: "QmZhTai6WjvYGjVZZXmDxLBDrRfmdx4MychBEWjdbq9ErQ",
        //         sitio: { x: 690, y: 150 },
        //         talla: { x: 100, y: 200 },
        //         escala: { x: 1.3, y: 1 },
        //         profundidad: 0,
        //       },
        //     ],
        //     profundidad: [
        //       {
        //         etiqueta: "monitores",
        //         uri: "QmbBJYZ8htPHLMkbg4dxzipGrTjsiaKui8xcPz4dTvqxzx",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 300,
        //           y: 190,
        //         },
        //         sitio: {
        //           x: 1000,
        //           y: 300,
        //         },
        //       },
        //       {
        //         uri: "QmNuXtWyyN1QDcveGJC1ykRsvaipTUh9XdxyMRLU3HFKYb",
        //         etiqueta: "estanteModa",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 450,
        //           y: 400,
        //         },
        //         sitio: {
        //           x: 1350,
        //           y: 460,
        //         },
        //       },
        //       {
        //         uri: "QmUGmUn6graG7ZfNyNJpYLBHswphoCMwzqMn8iBY15fCKM",
        //         etiqueta: "estanteInferior",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 340,
        //           y: 220,
        //         },
        //         sitio: {
        //           x: 250,
        //           y: 380,
        //         },
        //       },
        //       {
        //         etiqueta: "mesa",
        //         uri: "QmVSccor4cNbbKkbQfVJdi61Qzr7P27MAY8pZuRVDrWUki",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 650,
        //           y: 200,
        //         },
        //         sitio: {
        //           x: 700,
        //           y: 650,
        //         },
        //       },
        //     ],
        //     prohibited: [
        //       {
        //         width: 1512,
        //         height: 200,
        //         x: 0,
        //         y: 0,
        //       },
        //       {
        //         width: 200,
        //         height: 120,
        //         x: 1312,
        //         y: 200,
        //       },
        //       {
        //         width: 370,
        //         height: 90,
        //         x: 1050,
        //         y: 380,
        //       },
        //       {
        //         width: 450,
        //         height: 100,
        //         x: 1100,
        //         y: 450,
        //       },
        //       {
        //         width: 410,
        //         height: 100,
        //         x: 40,
        //         y: 380,
        //       },
        //       {
        //         width: 310,
        //         height: 60,
        //         x: 850,
        //         y: 260,
        //       },
        //       {
        //         width: 650,
        //         height: 90,
        //         x: 380,
        //         y: 560,
        //       },
        //     ],
        //     sillas: [
        //       {
        //         anim: Direccion.Sofa,
        //         profundidad: false,
        //         x_adjustado: 250,
        //         y_adjustado: 520,
        //         etiqueta: "sofaSuperior",
        //         sitio: { x: 250, y: 500 },
        //         talla: { x: 380, y: 170 },
        //         uri: "Qmf5HH5F4QgAKoAU4P3TZkNV6XzHWUF4LV8kND1JdYEPDp",
        //         escala: { x: 1, y: 1 },
        //       },
        //       {
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         x_adjustado: 930,
        //         y_adjustado: 665,
        //         etiqueta: "sillón1",
        //         sitio: { x: 930, y: 720 },
        //         talla: { x: 160, y: 175 },
        //         uri: "QmX44D6AKP4wmx7FYMgHXBRNPCRobaRLtYhe2wdeZZnf8s",
        //         escala: { x: 1, y: 1 },
        //         par: "mesa",
        //       },
        //       {
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         x_adjustado: 700,
        //         y_adjustado: 665,
        //         etiqueta: "sillón2",
        //         sitio: { x: 700, y: 720 },
        //         talla: { x: 140, y: 165 },
        //         uri: "QmQSXmTMDUuGKyaukg1TRN87kT81P9AjRUySbmmFJgncTw",
        //         escala: { x: 1, y: 1 },
        //         par: "mesa",
        //       },
        //       {
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         x_adjustado: 510,
        //         y_adjustado: 665,
        //         etiqueta: "sillón3",
        //         sitio: { x: 510, y: 720 },
        //         talla: { x: 189, y: 175 },
        //         uri: "Qme8NKnFn7qzQtfPw23VsRUcaJAAz8cqonU58rJ1Ny3kDH",
        //         escala: { x: 1, y: 1 },
        //         par: "mesa",
        //       },
        //     ],
        //     mundo: { height: 830, width: 1512 },
        //   },
        //   {
        //     clave: "boutique de ropa callejera",
        //     mundo: { height: 1200, width: 2000 },
        //     fondo: {
        //       uri: "QmaihjqdZER8BCZmTnVAfdeKUogNTCiRwrwEv14uLxbfr7",
        //       etiqueta: "fondo",
        //       displayHeight: 850,
        //       displayWidth: 2000,
        //       sitio: { x: 0, y: 350 },
        //     },
        //     objects: [
        //       {
        //         uri: "QmeWniogVfBhcG1Uu69ToheyxvLqgepzKqLkQc34EyqjKB",
        //         talla: { x: 2000, y: 350 },
        //         sitio: {
        //           x: 1000,
        //           y: 175,
        //         },
        //         etiqueta: "base",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //       },
        //       {
        //         etiqueta: "mezcla",
        //         uri: "QmTYHMzz6356SNeR6gCUcrEoXnXvtHkwPUNHiU3hEck3cR",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 1000, y: 500 },
        //         sitio: {
        //           x: 1000,
        //           y: 200,
        //         },
        //       },
        //       {
        //         etiqueta: "servidores",
        //         uri: "QmNpgdQ8b6eWMdxr91V3soT4pEeirHJo3q9JsGY7Lc1yoD",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 200, y: 250 },
        //         sitio: {
        //           x: 1850,
        //           y: 300,
        //         },
        //       },
        //       {
        //         etiqueta: "flora1",
        //         uri: "QmZZHARx1UMFH4zHMamyrqYYjta6ZasLzcsfNDJ5TgUC6c",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 89, y: 100 },
        //         sitio: {
        //           x: 1700,
        //           y: 1150,
        //         },
        //       },
        //       {
        //         etiqueta: "flora2",
        //         uri: "QmUEKgKQK8dz1bXM6r5opqRG4cV2M9CsDf6YvnYdogiTqU",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 89, y: 100 },
        //         sitio: {
        //           x: 1600,
        //           y: 1150,
        //         },
        //       },
        //       {
        //         etiqueta: "flora3",
        //         uri: "QmbR5Qoo5BH5Jb2ZBFbfTxbLtRXwgNf2dZzYHfZwJUhDyq",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 100, y: 120 },
        //         sitio: {
        //           x: 100,
        //           y: 1140,
        //         },
        //       },
        //     ],
        //     profundidad: [
        //       {
        //         uri: "QmSnhez8ns8uNh5SVNuUbSysTmFBBsEdjp9MXqKQNjnyHt",
        //         etiqueta: "callejero1",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 250, y: 200 },
        //         sitio: {
        //           x: 125,
        //           y: 500,
        //         },
        //       },
        //       {
        //         uri: "QmYuFskfLrHBVuiEqeCT9hZUnbmUPNp11SnoTAH8UDSu6b",
        //         etiqueta: "coser1",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 250, y: 200 },
        //         sitio: {
        //           x: 390,
        //           y: 500,
        //         },
        //       },
        //       {
        //         uri: "QmUJ8imvhzEDpYg4ua5CWpAHwoyhR6Fz7gKPrZ4isuWMaR",
        //         etiqueta: "callejero2",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 500, y: 200 },
        //         sitio: {
        //           x: 250,
        //           y: 700,
        //         },
        //       },
        //       {
        //         uri: "QmdgqzbMQTdXzjWL5QorjQwZ1v2CzXj4mbnfrSjE39a4hR",
        //         etiqueta: "callejero3",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 250, y: 200 },
        //         sitio: {
        //           x: 125,
        //           y: 900,
        //         },
        //       },
        //       {
        //         uri: "QmSa57Ty2stVHA6UCsUHqg7g5iiSqFWTt5KMdznHxHXcJh",
        //         etiqueta: "callejero4",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 250, y: 200 },
        //         sitio: {
        //           x: 1220,
        //           y: 500,
        //         },
        //       },
        //       {
        //         uri: "QmZn3GrcVJWmpL6uFYBw9zsSss7Y1viH6syNSracMmeXxQ",
        //         etiqueta: "coser2",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 250, y: 170 },
        //         sitio: {
        //           x: 930,
        //           y: 530,
        //         },
        //       },

        //       {
        //         etiqueta: "bricolaje",
        //         uri: "QmNfBuGJXvTaGKjLHT9zboso6HM4iwTNsLnnu4iyti3mcN",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 650, y: 300 },
        //         sitio: {
        //           x: 1100,
        //           y: 800,
        //         },
        //       },
        //       {
        //         etiqueta: "mesa2",
        //         uri: "QmeQkD3LBNmSXuNAHt3c9upiiYnAiRpZiGtS15wi8nbwrG",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 350, y: 200 },
        //         sitio: {
        //           x: 1800,
        //           y: 500,
        //         },
        //       },

        //       {
        //         uri: "QmaxnU8aGuNAoYRq2GcYPxnAshsgfT89L5g3ZSuooxg7ff",
        //         etiqueta: "callejero5",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 250, y: 200 },
        //         sitio: {
        //           x: 1870,
        //           y: 700,
        //         },
        //       },
        //       {
        //         uri: "QmSxxgxNQaZGoYBatY5sR1F7Nv6HbFmEx2vG5rLouts881",
        //         etiqueta: "coser3",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 110, y: 200 },
        //         sitio: {
        //           x: 1700,
        //           y: 700,
        //         },
        //       },
        //       {
        //         uri: "QmSGnSvi3omWMoFAe5gFgzErAjeWs3Rkkmmaw6MCTrgT6q",
        //         etiqueta: "café",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 110, y: 200 },
        //         sitio: {
        //           x: 1910,
        //           y: 1000,
        //         },
        //       },
        //       {
        //         uri: "QmPmpaf8dqYAABbHW4xD9hkqjZKFc3czSzTWNud4wQrqiN",
        //         etiqueta: "mesa3",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: { x: 450, y: 200 },
        //         sitio: {
        //           x: 1600,
        //           y: 1000,
        //         },
        //       },
        //     ],
        //     prohibited: [
        //       {
        //         width: 2000,
        //         height: 330,
        //         x: 0,
        //         y: 0,
        //       },
        //       {
        //         width: 550,
        //         height: 80,
        //         x: 0,
        //         y: 450,
        //       },
        //       {
        //         width: 550,
        //         height: 80,
        //         x: 0,
        //         y: 650,
        //       },

        //       {
        //         width: 270,
        //         height: 80,
        //         x: 0,
        //         y: 850,
        //       },
        //       {
        //         width: 600,
        //         height: 100,
        //         x: 800,
        //         y: 450,
        //       },
        //       {
        //         width: 750,
        //         height: 120,
        //         x: 700,
        //         y: 750,
        //       },

        //       {
        //         width: 700,
        //         height: 100,
        //         x: 1300,
        //         y: 900,
        //       },
        //       {
        //         width: 400,
        //         height: 100,
        //         x: 1600,
        //         y: 650,
        //       },
        //       {
        //         width: 400,
        //         height: 100,
        //         x: 1600,
        //         y: 450,
        //       },
        //     ],
        //     sillas: [
        //       {
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         x_adjustado: 1620,
        //         y_adjustado: 990,
        //         etiqueta: "sillita1",
        //         sitio: { x: 1620, y: 1050 },
        //         talla: { x: 110, y: 130 },
        //         uri: "QmNhsLtWepTR7igH4Wcqoh5VZ9a1PVwcE2mWTRA4czWnFN",
        //         escala: { x: 1, y: 1 },
        //         par: "mesa3",
        //       },
        //       {
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         x_adjustado: 1450,
        //         y_adjustado: 990,
        //         etiqueta: "sillita2",
        //         sitio: { x: 1450, y: 1050 },
        //         talla: { x: 110, y: 130 },
        //         uri: "QmT3SzD3XEoyxPfLZS9yQ1beHSpmdcfefk8BBDFzfjwV5T",
        //         escala: { x: 1, y: 1 },
        //         par: "mesa3",
        //       },
        //     ],
        //     cover: "QmUBJqUtcHZQRsrGHr8sM4UoCuKQWTUuhrXrpuVPyZBsBc",
        //     sprites: [
        //       {
        //         etiqueta: "muchacho-boutique",
        //         uri: "QmUHDrL3JTUMwztqyzr8cUdCjYLpjET9pRXrLTRPtfgSBx",
        //         x: 383,
        //         y: 576,
        //         cover: "QmXME5CUW3PdBVqsGx9JJznB1dWYUBbem1cmQgtEBX2vp7",
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 6,
        //       },
        //       {
        //         etiqueta: "chica-boutique",
        //         uri: "QmSXHXcEe9XWiVLL228NK12s9o68uWVQRVn8oedPE7boYf",
        //         cover: "QmczmZzdHG7fmYtCUDS58faHs1d1pzENEa3x8WxscyNhRH",
        //         x: 383,
        //         y: 576,
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 4,
        //       },
        //     ],
        //   },
        //   {
        //     clave: "microfábrica",
        //     cover: "QmXvZeMcQMdEHkKZL9U2CLpocMaKJvrfq644Zcsaybu5Q2",
        //     mundo: { height: 1200, width: 2300 },
        //     fondo: {
        //       uri: "QmZahhsTv8atePN1bWnH7DE9KFbreg93QhEb88dap5A2SA",
        //       etiqueta: "fondo",
        //       displayHeight: 900,
        //       displayWidth: 2300,
        //       sitio: { x: 0, y: 300 },
        //     },
        //     objects: [
        //       {
        //         uri: "QmWspbLDDaoAg9AnGt1qsHJ7uoRrraMeH18bLAS667tkrD",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 2300,
        //           y: 300,
        //         },
        //         etiqueta: "madera",
        //         sitio: {
        //           x: 1150,
        //           y: 150,
        //         },
        //       },
        //       {
        //         etiqueta: "escanar",
        //         uri: "Qmdx8bLozpJUtHhHHjYDHvrvVsSA9Kr2fW5PxTtbh2vR53",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 300,
        //           y: 350,
        //         },
        //         sitio: {
        //           x: 160,
        //           y: 250,
        //         },
        //       },
        //       {
        //         etiqueta: "fabricante",
        //         uri: "QmbD8KMDYNrSaKpWKFjQyzRXfb7i5hKgFFG6pcUqbCs3Uo",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 800,
        //           y: 300,
        //         },
        //         sitio: {
        //           x: 660,
        //           y: 250,
        //         },
        //       },
        //       {
        //         etiqueta: "cartel2",
        //         uri: "QmcMfY4sgqME7Wx93qhuPFdsebVTNs6axG6tD8dh3XTQ73",
        //         escala: { x: 1, y: 1 },
        //         sitio: { x: 2000, y: 1020 },
        //         talla: { x: 380, y: 290 },
        //       },
        //       {
        //         etiqueta: "plantaFuturística2",
        //         uri: "QmZKzF2sZThAi9QHFLqJPWWpkWh59x3Exje2At2MBTrHZ1",
        //         escala: { x: 1, y: 1 },
        //         sitio: { x: 1800, y: 1020 },
        //         talla: { x: 90, y: 90 },
        //       },
        //     ],
        //     profundidad: [
        //       {
        //         etiqueta: "impresor1",
        //         uri: "QmZ8cb23iMgtkG4F9yZAkCLq6tMSiUxtsDvAfnfanR27LH",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 100,
        //           y: 300,
        //         },
        //         sitio: {
        //           x: 2200,
        //           y: 300,
        //         },
        //       },
        //       {
        //         etiqueta: "impresor2",
        //         uri: "QmTMrRovTcyiZkQTdNVTRaZYWt743vtbApWsjLjF4UVdAk",
        //         escala: { x: 1, y: 1 },
        //         talla: { x: 700, y: 250 },
        //         sitio: {
        //           x: 400,
        //           y: 550,
        //         },
        //       },
        //       {
        //         etiqueta: "impresor3",
        //         uri: "Qmew8rEQRhQX3YtoVtm6MoUZkh7m2obtAZfoqKKe4VQJJw",
        //         escala: { x: 1, y: 1 },
        //         talla: { x: 400, y: 200 },
        //         sitio: {
        //           x: 1700,
        //           y: 580,
        //         },
        //       },
        //       {
        //         uri: "QmbPHiYrzvfXGahtpLHNMpM3ztNSK77f1ooVuScBaMWjzH",
        //         etiqueta: "dispositivo",
        //         escala: { x: 1, y: 1 },
        //         sitio: { x: 2100, y: 500 },
        //         talla: { x: 200, y: 250 },
        //       },
        //       {
        //         etiqueta: "ropas",
        //         uri: "QmPX1VfUfEjb3NoAh8KUZZmLZUHtWRyLhuyjsU2GDTXEms",
        //         escala: { x: 1, y: 1 },
        //         sitio: { x: 900, y: 900 },
        //         talla: { x: 500, y: 250 },
        //       },
        //       {
        //         etiqueta: "cartel1",
        //         uri: "Qma6p36Y8taGDjJf2xZ4X9pchWRJTWNyQPi9NsVbjarxbR",
        //         escala: { x: 1, y: 1 },
        //         sitio: { x: 300, y: 1000 },
        //         talla: { x: 450, y: 300 },
        //       },
        //       {
        //         etiqueta: "plantaFuturística1",
        //         uri: "QmbmQFFHFAAyXsSWgFByKWXCSrF1Q2kZbKqqPBKRaCCLJK",
        //         escala: { x: 1, y: 1 },
        //         sitio: { x: 600, y: 1100 },
        //         talla: { x: 90, y: 90 },
        //       },
        //     ],
        //     prohibited: [
        //       {
        //         width: 2300,
        //         height: 220,
        //         x: 0,
        //         y: 0,
        //       },
        //       {
        //         width: 300,
        //         height: 220,
        //         x: 0,
        //         y: 100,
        //       },
        //       {
        //         width: 800,
        //         height: 220,
        //         x: 300,
        //         y: 100,
        //       },
        //       {
        //         width: 800,
        //         height: 100,
        //         x: 1500,
        //         y: 270,
        //       },
        //       {
        //         x: 0,
        //         y: 450,
        //         width: 750,
        //         height: 150,
        //       },
        //       {
        //         x: 530,
        //         y: 630,
        //         width: 100,
        //         height: 100,
        //       },
        //       {
        //         x: 1500,
        //         y: 500,
        //         width: 800,
        //         height: 100,
        //       },
        //       {
        //         x: 2100,
        //         y: 400,
        //         width: 200,
        //         height: 100,
        //       },
        //       {
        //         x: 650,
        //         y: 800,
        //         width: 500,
        //         height: 100,
        //       },
        //       {
        //         x: 1750,
        //         y: 900,
        //         width: 550,
        //         height: 300,
        //       },
        //       {
        //         x: 0,
        //         y: 900,
        //         width: 520,
        //         height: 140,
        //       },
        //       {
        //         x: 560,
        //         y: 1100,
        //         width: 100,
        //         height: 100,
        //       },
        //     ],
        //     sillas: [
        //       {
        //         uri: "QmUBwCQeatnz4oz1AsnRFajjoGHRgASfCRU5dBhcHbJGvT",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         etiqueta: "camilla",
        //         profundidad: false,
        //         anim: Direccion.Sofa,
        //         x_adjustado: 1850,
        //         y_adjustado: 200,
        //         talla: { x: 500, y: 300 },
        //         sitio: {
        //           x: 1850,
        //           y: 300,
        //         },
        //       },
        //       {
        //         uri: "QmbhYArzZShSc1QUxoJHCpRLzEuA4B92xu6K5LAcKBCRuc",
        //         etiqueta: "banco1",
        //         profundidad: true,
        //         anim: Direccion.Silla,
        //         talla: { x: 90, y: 100 },
        //         sitio: {
        //           x: 600,
        //           y: 700,
        //         },
        //         x_adjustado: 600,
        //         y_adjustado: 610,
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //       },
        //     ],
        //     sprites: [
        //       {
        //         etiqueta: "muchacho-micro",
        //         uri: "QmUHDrL3JTUMwztqyzr8cUdCjYLpjET9pRXrLTRPtfgSBx",
        //         x: 383,
        //         y: 576,
        //         cover: "QmXME5CUW3PdBVqsGx9JJznB1dWYUBbem1cmQgtEBX2vp7",
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 6,
        //       },
        //       {
        //         etiqueta: "chica-micro",
        //         uri: "QmSXHXcEe9XWiVLL228NK12s9o68uWVQRVn8oedPE7boYf",
        //         cover: "QmczmZzdHG7fmYtCUDS58faHs1d1pzENEa3x8WxscyNhRH",
        //         x: 383,
        //         y: 576,
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 4,
        //       },
        //     ],
        //   },
        //   {
        //     clave: "agencia de llms",
        //     cover: "QmTs6DvEjiMzJHuXmtJBR13t53wo9TedjkymcFAT88qX78",
        //     fondo: {
        //       uri: "QmWUHw3f6256Xkw18Rq6J5XjDepS2X3RsCL2uHCEeoaDLv",
        //       etiqueta: "fondo",
        //       displayHeight: 700,
        //       displayWidth: 1512,
        //       sitio: { x: 0, y: 300 },
        //     },
        //     objects: [
        //       {
        //         etiqueta: "parteAtras",
        //         uri: "QmS58UDcPcGnQXipYAx2BCnAuGWD2RNJYTD8ukk6PAxxoX",
        //         sitio: {
        //           x: 756,
        //           y: 150,
        //         },
        //         talla: {
        //           x: 1512,
        //           y: 300,
        //         },
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //       },
        //       {
        //         etiqueta: "recreacion",
        //         uri: "QmX6MsiU8rHEhyAE8nQCL4esUN7xZxFaccXVbGZHyqLWUg",
        //         talla: {
        //           x: 400,
        //           y: 150,
        //         },
        //         sitio: {
        //           x: 1300,
        //           y: 300,
        //         },
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //       },
        //     ],

        //     profundidad: [
        //       {
        //         uri: "QmWNtMBq6BSLP41nmUwFKpXHqmU8rt9AnhpzpKc7EtyJAv",
        //         etiqueta: "cabinaDJ",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           y: 360,
        //           x: 200,
        //         },
        //         talla: {
        //           x: 300,
        //           y: 200,
        //         },
        //       },
        //       {
        //         uri: "QmPfPzfcFRjYcijD42qdLsWmHLW7dekU4wQ5qQK1G4ELuL",
        //         etiqueta: "almacenamientoPatineta",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           y: 360,
        //           x: 400,
        //         },
        //         talla: {
        //           x: 100,
        //           y: 200,
        //         },
        //       },
        //       {
        //         etiqueta: "eseñanzaRincón",
        //         uri: "QmedtK6fazjRHCmKRsB6pHSV8DW4Vn2edaqQZqB3wCSiLF",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           y: 570,
        //           x: 500,
        //         },
        //         talla: {
        //           x: 480,
        //           y: 210,
        //         },
        //       },
        //       {
        //         etiqueta: "mesaDeTrabajo1",
        //         uri: "QmWaGEbJCSRfdPC1fV3PeSnSUUQM8keSjTARJ4TCNYfx6N",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: {
        //           x: 250,
        //           y: 160,
        //         },
        //         sitio: {
        //           x: 850,
        //           y: 480,
        //         },
        //       },
        //       {
        //         etiqueta: "mesaDeTrabajo2",
        //         uri: "QmXBEDFhqgvxbwSRBBUHDVebCjEvcpznWxbm16jAEMr26n",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: {
        //           x: 250,
        //           y: 160,
        //         },
        //         sitio: {
        //           x: 1100,
        //           y: 480,
        //         },
        //       },
        //       {
        //         etiqueta: "mesaDeTrabajo3",
        //         uri: "QmTZCpyK66xR7vmMPeB6j1okT3sRf1NPALYXUnE6gs3gtW",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: {
        //           x: 250,
        //           y: 160,
        //         },
        //         sitio: {
        //           x: 1350,
        //           y: 480,
        //         },
        //       },
        //       {
        //         etiqueta: "impresito",
        //         uri: "QmQ21tBBTzje2LiE3SbPzWyjj56iH5gtMCcXsEGSzXuzFs",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: {
        //           y: 100,
        //           x: 100,
        //         },
        //         sitio: {
        //           x: 80,
        //           y: 850,
        //         },
        //       },
        //       {
        //         etiqueta: "ordenador1",
        //         uri: "QmNsxpVoDgKjUcLCSNEtMhVCxUi1XkbsaY16UwBHNRZrj1",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: {
        //           y: 200,
        //           x: 280,
        //         },
        //         sitio: {
        //           x: 280,
        //           y: 850,
        //         },
        //       },
        //       {
        //         etiqueta: "cajón",
        //         uri: "QmTFoN8mHstzX9tS1HsJ3tD1uAxJA3DNk7WHpqntTYiMac",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: {
        //           y: 200,
        //           x: 140,
        //         },
        //         sitio: {
        //           x: 500,
        //           y: 850,
        //         },
        //       },
        //       {
        //         etiqueta: "radio",
        //         uri: "QmXmr2hUCAbQu5TBdyXeyMNnr2o2iPYf9GMAHKzAbLeKnU",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 250,
        //           y: 210,
        //         },
        //         sitio: {
        //           x: 1400,
        //           y: 750,
        //         },
        //       },
        //       {
        //         etiqueta: "caja",
        //         uri: "QmVFcLk49jy64Xf2qnBzXknraVmU5B6nBmAc7qQKvZCFrZ",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 100,
        //           y: 190,
        //         },
        //         sitio: {
        //           x: 1240,
        //           y: 750,
        //         },
        //       },
        //       {
        //         etiqueta: "ordenador2",
        //         uri: "QmQ8EktWjZAhz8qgeNzQD43atLhbvJgRNpw3Jay4LcuZM4",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 240,
        //           y: 260,
        //         },
        //         sitio: {
        //           x: 1050,
        //           y: 750,
        //         },
        //       },
        //       {
        //         etiqueta: "estanteCallejero",
        //         uri: "QmdhBzR297vVvqfAgKGbu6H6uFEbnqrM5W13vE3DXy1cAU",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 200,
        //           y: 220,
        //         },
        //         sitio: {
        //           x: 1400,
        //           y: 880,
        //         },
        //       },
        //       {
        //         etiqueta: "plantita",
        //         uri: "QmYyBFD31N7V8uqseXqVnvR6tS5hHHrAcqnCEdijubAWhR",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 150,
        //           y: 160,
        //         },
        //         sitio: {
        //           x: 750,
        //           y: 920,
        //         },
        //       },
        //       {
        //         etiqueta: "altavoz",
        //         uri: "QmWi3qBSiEmUQCpQhfAPjnBP4DLayzb6KbHVrbgAy8frFx",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 150,
        //           y: 100,
        //         },
        //         sitio: {
        //           x: 900,
        //           y: 950,
        //         },
        //       },
        //     ],
        //     prohibited: [
        //       {
        //         width: 1512,
        //         height: 240,
        //         x: 0,
        //         y: 0,
        //       },
        //       {
        //         width: 300,
        //         height: 150,
        //         x: 790,
        //         y: 140,
        //       },
        //       {
        //         width: 400,
        //         height: 150,
        //         x: 1112,
        //         y: 160,
        //       },
        //       {
        //         y: 300,
        //         x: 50,
        //         width: 400,
        //         height: 90,
        //       },
        //       {
        //         y: 500,
        //         x: 0,
        //         width: 700,
        //         height: 90,
        //       },
        //       {
        //         y: 400,
        //         x: 712,
        //         width: 800,
        //         height: 90,
        //       },
        //       {
        //         width: 400,
        //         height: 90,
        //         x: 660,
        //         y: 910,
        //       },
        //       {
        //         y: 780,
        //         x: 0,
        //         width: 600,
        //         height: 100,
        //       },
        //       {
        //         y: 630,
        //         x: 900,
        //         width: 612,
        //         height: 130,
        //       },
        //       {
        //         y: 870,
        //         x: 1312,
        //         width: 200,
        //         height: 130,
        //       },
        //     ],
        //     sillas: [
        //       {
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         etiqueta: "sofaAmarillo",
        //         uri: "QmZ5EC8us6LuXkboTnXMGRhVwBLfasHmNfVLCypbUbdMK8",
        //         sitio: {
        //           x: 930,
        //           y: 295,
        //         },
        //         profundidad: false,
        //         anim: Direccion.Sofa,
        //         x_adjustado: 930,
        //         y_adjustado: 265,
        //         talla: {
        //           x: 300,
        //           y: 150,
        //         },
        //       },
        //       {
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         etiqueta: "sillitaIzquierda",
        //         uri: "QmXT7C9Qr21F4EDwd35GiyrsR7xYsHmwXZ3E6TyRYWD73h",
        //         sitio: {
        //           x: 130,
        //           y: 580,
        //         },
        //         profundidad: false,
        //         anim: Direccion.Sofa,
        //         x_adjustado: 160,
        //         y_adjustado: 560,
        //         talla: {
        //           x: 200,
        //           y: 180,
        //         },
        //       },
        //       {
        //         uri: "QmZhsyajhbNq3JbHqy3enc4byuCwuioYMjKipLuL5GGamA",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         profundidad: true,
        //         par: "mesaDeTrabajo1",
        //         anim: Direccion.Silla,
        //         etiqueta: "sillaDeTrabajo1",
        //         sitio: {
        //           x: 850,
        //           y: 550,
        //         },
        //         talla: {
        //           x: 100,
        //           y: 100,
        //         },
        //         x_adjustado: 850,
        //         y_adjustado: 510,
        //       },
        //       {
        //         uri: "QmZhsyajhbNq3JbHqy3enc4byuCwuioYMjKipLuL5GGamA",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         profundidad: true,
        //         par: "mesaDeTrabajo2",
        //         anim: Direccion.Silla,
        //         etiqueta: "sillaDeTrabajo2",
        //         sitio: {
        //           x: 1100,
        //           y: 550,
        //         },
        //         talla: {
        //           x: 100,
        //           y: 100,
        //         },
        //         x_adjustado: 1100,
        //         y_adjustado: 510,
        //       },
        //       {
        //         uri: "QmZhsyajhbNq3JbHqy3enc4byuCwuioYMjKipLuL5GGamA",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         profundidad: true,
        //         par: "mesaDeTrabajo3",
        //         anim: Direccion.Silla,
        //         etiqueta: "sillaDeTrabajo3",
        //         sitio: {
        //           x: 1350,
        //           y: 550,
        //         },
        //         talla: {
        //           x: 100,
        //           y: 100,
        //         },
        //         x_adjustado: 1350,
        //         y_adjustado: 510,
        //       },
        //       {
        //         uri: "QmZhsyajhbNq3JbHqy3enc4byuCwuioYMjKipLuL5GGamA",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         profundidad: true,
        //         par: "ordenador1",
        //         anim: Direccion.Silla,
        //         etiqueta: "sillaDeTrabajo4",
        //         sitio: {
        //           x: 280,
        //           y: 940,
        //         },
        //         talla: {
        //           x: 100,
        //           y: 100,
        //         },
        //         x_adjustado: 280,
        //         y_adjustado: 920,
        //       },
        //       {
        //         uri: "QmZhsyajhbNq3JbHqy3enc4byuCwuioYMjKipLuL5GGamA",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         profundidad: true,
        //         par: "ordenador2",
        //         anim: Direccion.Silla,
        //         etiqueta: "sillaDeTrabajo5",
        //         sitio: {
        //           x: 1050,
        //           y: 840,
        //         },
        //         talla: {
        //           x: 100,
        //           y: 100,
        //         },
        //         x_adjustado: 280,
        //         y_adjustado: 820,
        //       },
        //     ],
        //     mundo: { height: 1000, width: 1512 },
        //     sprites: [
        //       {
        //         etiqueta: "muchacho-agencia",
        //         uri: "QmUHDrL3JTUMwztqyzr8cUdCjYLpjET9pRXrLTRPtfgSBx",
        //         x: 383,
        //         y: 576,
        //         cover: "QmXME5CUW3PdBVqsGx9JJznB1dWYUBbem1cmQgtEBX2vp7",
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 6,
        //       },
        //       {
        //         etiqueta: "chica-agencia",
        //         uri: "QmSXHXcEe9XWiVLL228NK12s9o68uWVQRVn8oedPE7boYf",
        //         cover: "QmczmZzdHG7fmYtCUDS58faHs1d1pzENEa3x8WxscyNhRH",
        //         x: 383,
        //         y: 576,
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 4,
        //       },
        //     ],
        //   },

        //   {
        //     clave: "pub en ruinas",
        //     mundo: { height: 1500, width: 2000 },
        //     fondo: {
        //       uri: "QmVZ38f7115AUJwsgeoQ84YDGXwNQ8PmjLAuWZPnNNm7uy",
        //       etiqueta: "fondo",
        //       displayHeight: 1000,
        //       displayWidth: 2000,
        //       sitio: { x: 0, y: 500 },
        //     },
        //     cover: "QmWQMu5z5ho4prQv43Hdv27xtUtoUh78HukEPgCVEx3aLP",
        //     objects: [
        //       {
        //         etiqueta: "parteDeAtrás",
        //         uri: "QmPzut9FA8KSN6ChhioTiMdDmYKc32cBXAmVQrEa6aG9k7",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         talla: {
        //           x: 2000,
        //           y: 500,
        //         },
        //         sitio: {
        //           x: 1000,
        //           y: 250,
        //         },
        //       },
        //       {
        //         etiqueta: "bar",
        //         uri: "QmVheHZP2BCgfo92W1Dvp3NuhR7KEBrDu6PQmw6bv2TJu9",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 150,
        //           y: 560,
        //         },
        //         talla: {
        //           x: 300,
        //           y: 240,
        //         },
        //       },
        //       {
        //         etiqueta: "tableroDJ1",
        //         uri: "QmZx2T5Bx4jXUg8dpquNynGkgg4yyUHJYHcgTYQUUN31Gb",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 1450,
        //           y: 560,
        //         },
        //         talla: {
        //           x: 300,
        //           y: 340,
        //         },
        //       },
        //       {
        //         etiqueta: "tableroDJ2",
        //         uri: "QmdXrSVpmZcqjbD4qr4yV3dFfhWBPA8fLf4qffb3KEUM2t",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 1820,
        //           y: 560,
        //         },
        //         talla: {
        //           x: 300,
        //           y: 340,
        //         },
        //       },
        //       {
        //         etiqueta: "panel",
        //         uri: "QmdwKsvH4iEpnrr1cbexsTTeNVxRYVAdmMM1gT4LY82r14",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 900,
        //           y: 360,
        //         },
        //         talla: {
        //           x: 280,
        //           y: 220,
        //         },
        //       },
        //       {
        //         etiqueta: "sofita",
        //         uri: "QmariqaDCJ3y7nReenA7gNyhQ6HtrwirK18udcbNJcqvnH",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 600,
        //           y: 420,
        //         },
        //         talla: {
        //           x: 240,
        //           y: 110,
        //         },
        //       },
        //       {
        //         etiqueta: "dispositivoAleatorio1",
        //         uri: "QmQAge34nvvgQngzcd9r1Hiz3dsJR5C19F5WtfCzkut761",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 1850,
        //           y: 850,
        //         },
        //         talla: {
        //           x: 300,
        //           y: 290,
        //         },
        //       },
        //       {
        //         etiqueta: "dispositivoAleatorio2",
        //         uri: "Qma4zkw3MPTbHmiZeZPcmbclaveuRuVD8Q8e4QPdq3foYEQE",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 1930,
        //           y: 970,
        //         },
        //         talla: {
        //           x: 140,
        //           y: 250,
        //         },
        //       },
        //     ],
        //     profundidad: [
        //       {
        //         etiqueta: "mesaDeTaburetes",
        //         uri: "QmVEXmsobZYfHif6k34tY86BwiXdPq7DGVYQW4Mxqwv3KL",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 1000,
        //           y: 1000,
        //         },
        //         talla: {
        //           x: 900,
        //           y: 280,
        //         },
        //       },

        //       {
        //         etiqueta: "cartelIluminoso",
        //         uri: "QmQPUvhc9xXoSNECH1RJsKpWsqv95411WhApn8NgYFt8y9",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 1850,
        //           y: 1350,
        //         },
        //         talla: {
        //           x: 250,
        //           y: 315,
        //         },
        //       },
        //       {
        //         etiqueta: "zapatos",
        //         uri: "QmT13zWibYMJ6tYsdqwNJvX6FGNJCUs5eXTLp7YexVyfCf",
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 1600,
        //           y: 1400,
        //         },
        //         talla: {
        //           x: 210,
        //           y: 150,
        //         },
        //       },
        //       {
        //         escala: { x: 1, y: 1 },
        //         etiqueta: "mesaDeHerramientas",
        //         uri: "Qma7XechSmdquUth7BGhZpH7U9T9FzsJrXst5BFoYUzd7Z",
        //         sitio: {
        //           x: 175,
        //           y: 1200,
        //         },
        //         talla: {
        //           x: 250,
        //           y: 150,
        //         },
        //       },
        //       {
        //         escala: { x: 1, y: 1 },
        //         etiqueta: "cajaDeMúsica",
        //         uri: "QmWV2TQ3gbXFbNR5rTZQM2Y7e3xT43pviCaMK4K27bapJa",
        //         sitio: {
        //           x: 700,
        //           y: 1420,
        //         },
        //         talla: {
        //           x: 100,
        //           y: 120,
        //         },
        //       },
        //       {
        //         escala: { x: 1, y: 1 },
        //         etiqueta: "maniquí",
        //         uri: "QmSYN1e6nWeCTbexJWAkiaTP18evgAq5Z5wEngUPRow86a",
        //         sitio: {
        //           x: 500,
        //           y: 1350,
        //         },
        //         talla: {
        //           x: 260,
        //           y: 300,
        //         },
        //       },
        //       {
        //         etiqueta: "mesaDePie",
        //         uri: "QmeeHffDPNXQ4XXgAggDGy12srCs8kHWNqf9YPogTR2Lzw",
        //         escala: { x: 1, y: 1 },
        //         sitio: {
        //           x: 780,
        //           y: 600,
        //         },
        //         talla: {
        //           x: 400,
        //           y: 250,
        //         },
        //       },
        //       {
        //         etiqueta: "taburete4",
        //         uri: "QmcWeWeNCwSzUozA3euG7n1pE5aFZST6Sr9ALUrUJaaPYH",
        //         escala: { x: 1, y: 1 },
        //         sitio: {
        //           x: 500,
        //           y: 580,
        //         },
        //         talla: {
        //           x: 120,
        //           y: 170,
        //         },
        //       },
        //       {
        //         etiqueta: "taburete5",
        //         uri: "QmZVhMo18vUUoKWACDkHWMU5qjFXyFqqCDYpatC9ZQPFwg",
        //         escala: { x: 1, y: 1 },
        //         sitio: {
        //           x: 1000,
        //           y: 700,
        //         },
        //         talla: {
        //           x: 120,
        //           y: 170,
        //         },
        //       },
        //       {
        //         etiqueta: "taburete6",
        //         uri: "QmcKnVhqZL5vPQqcDYjwmHwC4WoYeJFpynha2TDJ11Znyw",
        //         escala: { x: 1, y: 1 },
        //         sitio: {
        //           x: 750,
        //           y: 700,
        //         },
        //         talla: {
        //           x: 120,
        //           y: 170,
        //         },
        //       },
        //     ],
        //     prohibited: [
        //       {
        //         width: 2000,
        //         height: 300,
        //         x: 0,
        //         y: 0,
        //       },
        //       {
        //         width: 300,
        //         height: 600,
        //         x: 0,
        //         y: 0,
        //       },
        //       {
        //         width: 600,
        //         height: 420,
        //         x: 450,
        //         y: 0,
        //       },
        //       {
        //         width: 300,
        //         height: 350,
        //         x: 1700,
        //         y: 750,
        //       },
        //       {
        //         width: 600,
        //         height: 250,
        //         x: 1400,
        //         y: 1250,
        //       },
        //       {
        //         width: 400,
        //         height: 200,
        //         x: 400,
        //         y: 1300,
        //       },
        //       {
        //         width: 430,
        //         height: 100,
        //         x: 0,
        //         y: 1150,
        //       },
        //       {
        //         width: 870,
        //         height: 170,
        //         x: 580,
        //         y: 900,
        //       },
        //       {
        //         width: 700,
        //         height: 200,
        //         x: 450,
        //         y: 530,
        //       },
        //       {
        //         width: 260,
        //         height: 170,
        //         x: 1330,
        //         y: 450,
        //       },
        //       {
        //         width: 320,
        //         height: 180,
        //         x: 1680,
        //         y: 460,
        //       },
        //     ],
        //     sillas: [
        //       {
        //         etiqueta: "taburete1",
        //         uri: "QmT4SbbozzbmL5hWwVUNeRSTWMtEtKUH1MmiLPgnfxpUQR",
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 700,
        //           y: 1150,
        //         },
        //         talla: {
        //           x: 120,
        //           y: 150,
        //         },
        //         x_adjustado: 700,
        //         y_adjustado: 1000,
        //         par: "mesaDeTaburetes",
        //       },
        //       {
        //         etiqueta: "taburete2",
        //         uri: "QmT4SbbozzbmL5hWwVUNeRSTWMtEtKUH1MmiLPgnfxpUQR",
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 1000,
        //           y: 1150,
        //         },
        //         talla: {
        //           x: 120,
        //           y: 150,
        //         },
        //         x_adjustado: 1000,
        //         y_adjustado: 1000,
        //         par: "mesaDeTaburetes",
        //       },
        //       {
        //         etiqueta: "taburete3",
        //         uri: "QmT4SbbozzbmL5hWwVUNeRSTWMtEtKUH1MmiLPgnfxpUQR",
        //         anim: Direccion.Silla,
        //         profundidad: true,
        //         escala: {
        //           x: 1,
        //           y: 1,
        //         },
        //         sitio: {
        //           x: 1300,
        //           y: 1150,
        //         },
        //         talla: {
        //           x: 120,
        //           y: 150,
        //         },
        //         x_adjustado: 1300,
        //         y_adjustado: 1050,
        //         par: "mesaDeTaburetes",
        //       },
        //       {
        //         escala: { x: 1, y: 1 },
        //         profundidad: false,
        //         anim: Direccion.Sofa,
        //         etiqueta: "cátedra",
        //         uri: "QmbXopW1B1PV5LeyW91Zjf3oaVM6UG7Lp9ViraQgrtTFKW",
        //         sitio: {
        //           x: 350,
        //           y: 1200,
        //         },
        //         talla: {
        //           x: 180,
        //           y: 200,
        //         },
        //         x_adjustado: 350,
        //         y_adjustado: 1000,
        //       },
        //     ],
        //     sprites: [
        //       {
        //         etiqueta: "muchacho-pub",
        //         uri: "QmUHDrL3JTUMwztqyzr8cUdCjYLpjET9pRXrLTRPtfgSBx",
        //         x: 383,
        //         y: 576,
        //         cover: "QmXME5CUW3PdBVqsGx9JJznB1dWYUBbem1cmQgtEBX2vp7",
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 6,
        //       },
        //       {
        //         etiqueta: "chica-pub",
        //         uri: "QmSXHXcEe9XWiVLL228NK12s9o68uWVQRVn8oedPE7boYf",
        //         cover: "QmczmZzdHG7fmYtCUDS58faHs1d1pzENEa3x8WxscyNhRH",
        //         x: 383,
        //         y: 576,
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 4,
        //       },
        //     ],
        //   },
        //   {
        //     clave: "marketing de contenido",
        //     fondo: {
        //       uri: "QmYZ6w8ebp4LijMwMwURWvBrxhYLgmfzUQUdAhSwJ18JRD",
        //       etiqueta: "fondo",
        //       displayHeight: 600,
        //       displayWidth: 1512,
        //       sitio: { x: 0, y: 230 },
        //     },
        //     cover: "Qmdriz9gdKL7riwkwagguFZLCZ56fPRo171i8MhvXuUAdx",
        //     objects: [
        //       {
        //         etiqueta: "ladrillos",
        //         uri: "QmNv6YFKdufAFg7Ay8dXt2MqD6362xhhR2d8xpAAUJoHzX",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           y: 230,
        //           x: 1512,
        //         },
        //         sitio: {
        //           x: 756,
        //           y: 115,
        //         },
        //       },

        //       {
        //         etiqueta: "floresiluminosas",
        //         uri: "QmNiyyS6SzTp6JnbHZLSSGcMS6acaonzeAjhTccHM4j45c",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 180,
        //           y: 170,
        //         },
        //         sitio: {
        //           x: 390,
        //           y: 200,
        //         },
        //       },
        //       {
        //         etiqueta: "patineta",
        //         uri: "QmSqTTx4EUvrU1mqejqb37npumMQHZL93btZS7fu7KVeg6",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 250,
        //           y: 180,
        //         },
        //         sitio: {
        //           x: 700,
        //           y: 200,
        //         },
        //       },
        //       {
        //         etiqueta: "sudaderas",
        //         uri: "QmPaBviJn15di5XJPxBspXcZu4H7q3Pig7YRJkpLZjTYvV",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 180,
        //           y: 200,
        //         },
        //         sitio: {
        //           x: 1410,
        //           y: 200,
        //         },
        //       },
        //     ],
        //     profundidad: [
        //       {
        //         etiqueta: "cajaDeEnseñanza",
        //         uri: "Qmd64MnZxL3wmYyQQZpV7QyhvhtuKxiThEi3CGweK4KjyL",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 270,
        //           y: 240,
        //         },
        //         sitio: {
        //           x: 150,
        //           y: 550,
        //         },
        //       },
        //       {
        //         etiqueta: "máquinaMezcla",
        //         uri: "QmYvJde47HGjZvaXehWEZDeb3kkdMeWBSZFbsuAqjCBPEC",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 230,
        //           y: 210,
        //         },
        //         sitio: {
        //           x: 480,
        //           y: 550,
        //         },
        //       },
        //       {
        //         etiqueta: "flores",
        //         uri: "QmUHSfHBznKnpfL1gPeK7B3ciJe7MyhZRbKdPZM3V3oWCb",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 120,
        //           y: 180,
        //         },
        //         sitio: {
        //           x: 305,
        //           y: 480,
        //         },
        //       },
        //       {
        //         etiqueta: "mesilla1",
        //         uri: "QmYP8ZC6X43jMAa364BofdLxAd6fWFfCKtKY6gauUaxRTC",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 100,
        //           y: 120,
        //         },
        //         sitio: {
        //           x: 315,
        //           y: 750,
        //         },
        //       },
        //       {
        //         etiqueta: "máquinaCoser",
        //         uri: "QmXclaveFHZRc2mTr7Djg1CxQrYTVWPLBDCNWrD18fM9uh6a",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 210,
        //           y: 170,
        //         },
        //         sitio: {
        //           x: 500,
        //           y: 750,
        //         },
        //       },
        //       {
        //         uri: "QmaRSfjAKFz9aB2q1fyCPoUy1V1NQnvHG3QwpmCDawNpou",
        //         etiqueta: "mesilla2",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 270,
        //           y: 240,
        //         },
        //         sitio: {
        //           x: 1360,
        //           y: 380,
        //         },
        //       },
        //       {
        //         etiqueta: "mesillaDeHerramientas",
        //         uri: "QmVReRSMwNPCxf45afceaZKA1KQR6o3zEpD7uVPXZ11qMF",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 200,
        //           y: 210,
        //         },
        //         sitio: {
        //           x: 1400,
        //           y: 700,
        //         },
        //       },
        //       {
        //         etiqueta: "armario",
        //         uri: "QmNShbcuWE7sBHDn7x4fRa5xrAN7eG3848GX1mTLYEYGbi",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 180,
        //           y: 240,
        //         },
        //         sitio: {
        //           x: 1200,
        //           y: 700,
        //         },
        //       },

        //       {
        //         etiqueta: "escritorioDeTrabajo",
        //         uri: "QmaZmDJzMrteXuRWuBxp4PA9teRxatkpyq67fNgaU94wDa",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           x: 250,
        //           y: 260,
        //         },
        //         sitio: {
        //           x: 1000,
        //           y: 700,
        //         },
        //       },
        //     ],
        //     prohibited: [
        //       {
        //         x: 0,
        //         y: 0,
        //         width: 1512,
        //         height: 190,
        //       },
        //       {
        //         x: 1300,
        //         y: 100,
        //         width: 212,
        //         height: 150,
        //       },
        //       {
        //         x: 550,
        //         y: 110,
        //         width: 290,
        //         height: 100,
        //       },
        //       {
        //         x: 850,
        //         y: 330,
        //         width: 682,
        //         height: 100,
        //       },
        //       {
        //         x: 0,
        //         y: 460,
        //         width: 650,
        //         height: 130,
        //       },
        //       {
        //         x: 300,
        //         y: 730,
        //         width: 300,
        //         height: 100,
        //       },
        //       {
        //         x: 862,
        //         y: 630,
        //         width: 650,
        //         height: 200,
        //       },
        //     ],
        //     sillas: [
        //       {
        //         etiqueta: "sofita1",
        //         uri: "QmafPkGnTM7FzN5tCNmmgbLSLrGBKhDieBBcZ5ogfcHcXt",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           y: 160,
        //           x: 300,
        //         },
        //         sitio: {
        //           x: 150,
        //           y: 200,
        //         },
        //         profundidad: false,
        //         anim: Direccion.Sofa,
        //         x_adjustado: 150,
        //         y_adjustado: 150,
        //       },
        //       {
        //         etiqueta: "sofita2",
        //         uri: "QmdU4MaEZsoZ2goXxiuHuiKg3RmRWGCRaQ7EnRfd1rVkG9",
        //         escala: { x: 1, y: 1 },
        //         talla: {
        //           y: 175,
        //           x: 300,
        //         },
        //         sitio: {
        //           x: 1100,
        //           y: 410,
        //         },
        //         profundidad: false,
        //         anim: Direccion.Sofa,
        //         x_adjustado: 1100,
        //         y_adjustado: 330,
        //       },
        //     ],
        //     mundo: { height: 830, width: 1512 },
        //     sprites: [
        //       {
        //         etiqueta: "muchacho-contenido",
        //         uri: "QmUHDrL3JTUMwztqyzr8cUdCjYLpjET9pRXrLTRPtfgSBx",
        //         x: 383,
        //         y: 576,
        //         cover: "QmXME5CUW3PdBVqsGx9JJznB1dWYUBbem1cmQgtEBX2vp7",
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 6,
        //       },
        //       {
        //         etiqueta: "chica-contenido",
        //         uri: "QmSXHXcEe9XWiVLL228NK12s9o68uWVQRVn8oedPE7boYf",
        //         cover: "QmczmZzdHG7fmYtCUDS58faHs1d1pzENEa3x8WxscyNhRH",
        //         x: 383,
        //         y: 576,
        //         displayHeight: 600,
        //         displayWidth: 300,
        //         frameWidth: 600,
        //         frameHeight: 600,
        //         margin: 0,
        //         startFrame: 0,
        //         endFrame: 143,
        //         escala: { x: 0.5, y: 0.5 },
        //         maxMoves: 4,
        //       },
        //     ],
        //   },
    ]
});
